# name: Laravel
# on: push
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Git checkout
#         uses: actions/checkout@v1
#       - name: Check Branch
#         run: echo ${GITHUB_REF##*/}
